# Generated by Django 3.2.6 on 2023-03-19 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20230319_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='places.category'),
        ),
        migrations.AlterField(
            model_name='request',
            name='date_approved',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='places.category'),
        ),
    ]
