# Generated by Django 3.2.6 on 2023-03-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20230319_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='imageurl',
            field=models.URLField(blank=True),
        ),
    ]
