# Generated by Django 3.2.6 on 2023-03-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_alter_request_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='date_approved',
            field=models.DateField(blank=True, null=True),
        ),
    ]
