# Generated by Django 3.2.6 on 2023-04-22 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_auto_20230422_0712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='tags',
        ),
    ]
