# Generated by Django 3.2.6 on 2023-04-22 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_remove_request_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='request',
            name='category',
        ),
        migrations.RemoveField(
            model_name='request',
            name='date_approved',
        ),
        migrations.RemoveField(
            model_name='request',
            name='imageurl',
        ),
    ]
