# Generated by Django 3.2.6 on 2023-04-22 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_auto_20230422_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='address',
            field=models.TextField(),
        ),
    ]
