# Generated by Django 3.2.6 on 2023-04-22 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_alter_request_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='places.address'),
        ),
    ]
