# Generated by Django 3.2.6 on 2023-05-23 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0013_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='date_approved',
            field=models.DateField(blank=True, null=True),
        ),
    ]
