# Generated by Django 3.2.6 on 2023-05-23 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0014_auto_20230523_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='date_created',
            field=models.DateField(editable=False),
        ),
    ]
