# Generated by Django 3.2.6 on 2023-05-23 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0015_alter_request_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='date_updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
