# Generated by Django 3.2.6 on 2023-05-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0016_auto_20230523_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='approved',
            field=models.BooleanField(auto_created=True, default=False),
        ),
    ]
