# Generated by Django 3.2.6 on 2023-05-23 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0017_alter_request_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='date_approved',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
