# Generated by Django 3.2.6 on 2023-05-23 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0018_auto_20230523_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='approved_by',
            field=models.CharField(auto_created=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='request',
            name='approved_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
