# Generated by Django 3.2.6 on 2023-05-23 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0019_auto_20230523_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='approved_by',
            field=models.CharField(auto_created=True, blank=True, max_length=100, null=True),
        ),
    ]
