# Generated by Django 3.2.6 on 2023-05-24 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0020_alter_request_approved_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
